# Generated by Django 2.1.7 on 2019-04-23 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyCriticEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FantasyCriticUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('discord_username', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('cover', models.IntegerField()),
                ('release_date', models.DateTimeField()),
                ('hypes', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='fantasycriticentry',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gamecalendar.Game'),
        ),
        migrations.AddField(
            model_name='fantasycriticentry',
            name='user',
            field=models.ManyToManyField(to='gamecalendar.FantasyCriticUser'),
        ),
    ]
